blueprint:
  name: Ring Keypad v2 Sounds, ZwaveJS
  domain: script
  input:
    keypad:
      name: Silence Ring Keypad Device Detected Sound *
      description: The device entry for the Ring keypad
      selector:
        device:
          manufacturer: Ring
          integration: zwave_js
          multiple: true
    sound_selection:
      name: Keypad Sound *
      description: > 
        Choose the sound to play. 
        
        
        

      default: "96"
      selector:
        select:
          mode: list
          options:
            - label: Silence Water Detected 
              value: "21"
            - label: Silence Low Temperature Detected 
              value: "20"              

mode: single

sequence:
  - service: zwave_js.set_value
    target:
      device_id: !input keypad
    data:
      command_class: 135
      endpoint: 0
      property: !input sound_selection
      property_key: 1
      value: 0
