blueprint:
  name: Ring Keypad v2 Sounds, exit and entry delay
  domain: script
  input:
    keypad:
      name: Ring Keypad Device *
      description: The device entry for the Ring keypad
      selector:
        device:
          manufacturer: Ring
          integration: zwave_js
          multiple: false
    sound_selection:
      name: Keypad Sound *
      description: > 
        Choose the sound to play. 
        
        
      
      default: "96"
      selector:
        select:
          mode: list
          options:
            - label: entry delay
              value: "17"
            - label: exit delay
              value: "18"

    sound_volume:
      name: Length *
      description: Choose the lenth of the delay.
      default: 30
      selector:
        number:
          min: 10
          max: 120
          step: 5
          unit_of_measurement: 'seconds'
          mode: slider

mode: single

sequence:
  - service: zwave_js.set_value
    target:
      device_id: !input keypad
    data:
      command_class: 135
      endpoint: 0
      property: !input sound_selection
      property_key: 9
      value: !input sound_volume
