blueprint:
  name: Ring Keypad v2 Sounds, ZwaveJS
  domain: script
  input:
    keypad:
      name: Ring Keypad Device *
      description: The device entry for the Ring keypad
      selector:
        device:
          manufacturer: Ring
          integration: zwave_js
          multiple: true
    sound_selection:
      name: Keypad Sound *
      description: > 
        Choose the sound to play. 
        
        
        
        WARNING: The **Alarm** options will not stop until the keypad mode is changed.
      default: "96"
      selector:
        select:
          mode: list
          options:
            - label: "*Alarm* Carbon Monoxide"
              value: "15"
            - label: "*Alarm* Fire"
              value: "14"
            - label: "*Alarm* Medical"
              value: "19"
            - label: "*Alarm* Police"
              value: "13"
            - label: Water Detected 
              value: "21"
            - label: Low Temperature Detected 
              value: "20"              
            - label: Ding Dong
              value: "96"
            - label: Echoing Bing Bong
              value: "99"
            - label: Error Tone
              value: "9"
            - label: Guitar Riff
              value: "97"
            - label: Doorbell Chime
              value: "100"
            - label: Wind Chimes
              value: "98"
    sound_volume:
      name: Keypad Volume *
      description: Choose the volume to play the sound.
      default: 50
      selector:
        number:
          min: 0
          max: 100
          step: 5
          unit_of_measurement: '%'
          mode: slider

mode: single

sequence:
  - service: zwave_js.set_value
    target:
      device_id: !input keypad
    data:
      command_class: 135
      endpoint: 0
      property: !input sound_selection
      property_key: 1
      value: 0
